name: User Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/my-buddy-backend-services/user-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build User Service with Maven
      run: |
        cd apps/my-buddy-backend-services/user-service
        mvn clean package -DskipTests
